services:
  - postgresql

before_script:
  - psql -c 'create database chitter_test;' -U postgres

script:
  - bundle exec rspec
  - rake db:create
  - rake db:migrate
  - rake db:migrate RACK_ENV=test
