services:
  - postgresql

before_script:
  - bundle
  - psql -c 'create database chitter_test;' -U postgres
  - rake db:create
  - rake db:migrate
  - rake db:migrate RACK_ENV=test

script:
  - bundle exec rspec

